### ISSUE TITLE
Feature request: add `requireEnv`, `getEnvOrThrow`, or similar

### ISSUE THREAD

**Issue by knpwrs** [cross-org/env#1]
I wrote a package a while back to enforce the presence of an environment variable and `throw` otherwise so that when dealing with environment variables that must be defined, the developer never had to narrow down from `undefined | string`: https://github.com/knpwrs/envariant

I love the idea of `@cross/env`, and would love it even more if it included similar functionality so I could deprecate my package.

**Comment by Pinta365** [comment]
Nice that you like the idea. I could most certainly implement that unless you want to get your hands dirty and open a PR with the implementation. Let me know :)

I think I like the `requireEnv` name best. Close to the already implemented `hasEnv` function.
